enum AST {
    PROGRAM                 ='PROGRAM',
    BLOCK                   ='BLOCK',

    STAT_UNKNOW             ='UNKNOW_STATEMENT',
    STAT_IF                 ='IF_STATEMENT',
    STAT_WHILE              ='WHILE_STATEMENT',
    STAT_FOR                ='FOR_STATEMENT',
    STAT_LOOP               ='LOOP_STATEMENT',
    STAT_SWITCH             ='SWITCH_STATEMENT',
    STAT_ASSIGN             ='ASSIGN_STATEMENT',
    STAT_UNKNOW_ID          ='UNDECLARED IDENTIFIER WITH MEMBERS',
    STAT_FUNCTION           ='FUNCTION_STATEMENT',
    STAT_RETURN             ='RETURN_STATEMENT',
    STAT_DISPOSE            ='DISPOSE_STATEMENT',
    STAT_EMIT               ='EMIT_STATEMENT',
    STAT_ON                 ='ON_STATEMENT',
    STAT_WAIT               ='WAIT_STATEMENT',

    EXPR_BINOP_COMPARE      ='COMPARATOR_EXPRESSION',
    EXPR_BINOP_ADDSUB       ='ADDSUB_EXPRESSION',
    EXPR_BINOP_MULTDIV      ='MULTDIV_EXPRESSION',

    EXPR_UNOP_PREUNOP       ='PREUNOP_EXPRESSION',
    EXPR_UNOP_PRE_TRUE      ='TRUE',
    EXPR_UNOP_PRE_FALSE     ='FALSE',
    EXPR_UNOP_PRE_NULL      ='NULL',
    EXPR_UNOP_PRE_UNKNOW    ='UNKNOW_UNARY_EXPRESSION',
    EXPR_UNOP_POST          ='POSTUNOP_EXPRESSION',
    EXPR_UNOP_POST_UNKNOW   ='UNKNOW_POSTFIX_EXPRESSION',

    EXPR_MEMBER_ID          ='ID_MEMBER_EXPRESSION',
    EXPR_MEMBER_UNKNOW      ='UNKNOW_MEMBER_EXPRESSION',
    EXPR_MEMBER_INDEXED     ='INDEXED_EXPRESSION',
    EXPR_MEMBER_METHOD_DECL ='METHOD_DECLARATION_EXPRESSION',
    EXPR_MEMBER_FUNC_DECL   ='FUNCTION_DECLARATION_EXPRESSION',
    EXPR_MEMBER_FUNC_CALL   ='FUNCTION_CALL_EXPRESSION',
    EXPR_MEMBER_ATTRIBUTE   ='ATTRIBUTE_EXPRESSION',
    // EXPR_MEMBER_UNKNOW_ITEM ='UNKNOW_MEMBER_ITEM_EXPRESSION',

    EXPR_PRIMARY_STRING     ='STRING',
    EXPR_PRIMARY_INTEGER    ='INTEGER',
    EXPR_PRIMARY_FLOAT      ='FLOAT',
    EXPR_PRIMARY_BIGINTEGER ='BIGINTEGER',
    EXPR_PRIMARY_BIGFLOAT   ='BIGFLOAT',
    EXPR_PRIMARY_UNKNOW     ='UNKNOW_EXPRESSION',

    EXPR_PARENTHESIS        ='PARENTHESIS_EXPRESSION',

    EXPR_TYPE_ID            ='TYPE_ID_EXPRESSION',
    EXPR_RECORD             ='RECORD_EXPRESSION',
    EXPR_ARGS               ='ARGS_EXPRESSION',
    EXPR_ARGS_IDS           ='ARGIDS_EXPRESSION',
    EXPR_ARRAY              ='ARRAY_EXPRESSION',
    EXPR_BINOP              ='BINOP'
}

export default AST;