export const TYPES = {
    INTEGER:'INTEGER',
    FLOAT:'FLOAT',
    BIGINTEGER:'BIGINTEGER',
    BIGFLOAT:'BIGFLOAT',
    
    BOOLEAN:'BOOLEAN',
    STRING:'STRING',
    NULL:'NULL',
    ARRAY:'ARRAY',
    UNKNOW:'UNKNOW',
    ERROR:'ERROR',
    KEYWORD:'KEYWORD',

    ATTRIBUTE_ID:'ATTRIBUTE_IDENTIFIER',
    METHOD_ID:'METHOD_IDENTIFIER',
    FUNCTION_ID:'FUNCTION_IDENTIFIER',
    VARIABLE_ID:'VARIABLE_IDENTIFIER',
    CONSTANT_ID:'CONSTANT_IDENTIFIER',

    OTHER_ID:'OTHER_IDENTIFIER'
}
export default TYPES;


export const BINOP_TYPES = new Map<string,string>();

// ADD
BINOP_TYPES.set('+' + TYPES.INTEGER + TYPES.INTEGER,      TYPES.INTEGER);
BINOP_TYPES.set('+' + TYPES.INTEGER + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('+' + TYPES.INTEGER + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
BINOP_TYPES.set('+' + TYPES.INTEGER + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.INTEGER + TYPES.STRING,       TYPES.STRING);

BINOP_TYPES.set('+' + TYPES.FLOAT   + TYPES.INTEGER,      TYPES.FLOAT);
BINOP_TYPES.set('+' + TYPES.FLOAT   + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('+' + TYPES.FLOAT   + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.FLOAT   + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.FLOAT   + TYPES.STRING,       TYPES.STRING);

BINOP_TYPES.set('+' + TYPES.BIGINTEGER + TYPES.INTEGER,    TYPES.BIGINTEGER);
BINOP_TYPES.set('+' + TYPES.BIGINTEGER + TYPES.FLOAT,      TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGINTEGER + TYPES.BIGINTEGER, TYPES.BIGINTEGER);
BINOP_TYPES.set('+' + TYPES.BIGINTEGER + TYPES.BIGFLOAT,   TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGINTEGER + TYPES.STRING,     TYPES.STRING);

BINOP_TYPES.set('+' + TYPES.BIGFLOAT + TYPES.INTEGER,      TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGFLOAT + TYPES.FLOAT,        TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGFLOAT + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGFLOAT + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);
BINOP_TYPES.set('+' + TYPES.BIGFLOAT + TYPES.STRING,       TYPES.STRING);

// SUB
BINOP_TYPES.set('-' + TYPES.INTEGER + TYPES.INTEGER,      TYPES.INTEGER);
BINOP_TYPES.set('-' + TYPES.INTEGER + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('-' + TYPES.INTEGER + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
BINOP_TYPES.set('-' + TYPES.INTEGER + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('-' + TYPES.FLOAT   + TYPES.INTEGER,      TYPES.FLOAT);
BINOP_TYPES.set('-' + TYPES.FLOAT   + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('-' + TYPES.FLOAT   + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('-' + TYPES.FLOAT   + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('-' + TYPES.BIGINTEGER + TYPES.INTEGER,    TYPES.BIGINTEGER);
BINOP_TYPES.set('-' + TYPES.BIGINTEGER + TYPES.FLOAT,      TYPES.BIGFLOAT);
BINOP_TYPES.set('-' + TYPES.BIGINTEGER + TYPES.BIGINTEGER, TYPES.BIGINTEGER);
BINOP_TYPES.set('-' + TYPES.BIGINTEGER + TYPES.BIGFLOAT,   TYPES.BIGFLOAT);

BINOP_TYPES.set('-' + TYPES.BIGFLOAT + TYPES.INTEGER,      TYPES.BIGFLOAT);
BINOP_TYPES.set('-' + TYPES.BIGFLOAT + TYPES.FLOAT,        TYPES.BIGFLOAT);
BINOP_TYPES.set('-' + TYPES.BIGFLOAT + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('-' + TYPES.BIGFLOAT + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

// MUL
BINOP_TYPES.set('*' + TYPES.INTEGER + TYPES.INTEGER,      TYPES.INTEGER);
BINOP_TYPES.set('*' + TYPES.INTEGER + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('*' + TYPES.INTEGER + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
BINOP_TYPES.set('*' + TYPES.INTEGER + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('*' + TYPES.FLOAT   + TYPES.INTEGER,      TYPES.FLOAT);
BINOP_TYPES.set('*' + TYPES.FLOAT   + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('*' + TYPES.FLOAT   + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('*' + TYPES.FLOAT   + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('*' + TYPES.BIGINTEGER + TYPES.INTEGER,    TYPES.BIGINTEGER);
BINOP_TYPES.set('*' + TYPES.BIGINTEGER + TYPES.FLOAT,      TYPES.BIGFLOAT);
BINOP_TYPES.set('*' + TYPES.BIGINTEGER + TYPES.BIGINTEGER, TYPES.BIGINTEGER);
BINOP_TYPES.set('*' + TYPES.BIGINTEGER + TYPES.BIGFLOAT,   TYPES.BIGFLOAT);

BINOP_TYPES.set('*' + TYPES.BIGFLOAT + TYPES.INTEGER,      TYPES.BIGFLOAT);
BINOP_TYPES.set('*' + TYPES.BIGFLOAT + TYPES.FLOAT,        TYPES.BIGFLOAT);
BINOP_TYPES.set('*' + TYPES.BIGFLOAT + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('*' + TYPES.BIGFLOAT + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

// DIV
BINOP_TYPES.set('/' + TYPES.INTEGER + TYPES.INTEGER,      TYPES.FLOAT);
BINOP_TYPES.set('/' + TYPES.INTEGER + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('/' + TYPES.INTEGER + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.INTEGER + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('/' + TYPES.FLOAT   + TYPES.INTEGER,      TYPES.FLOAT);
BINOP_TYPES.set('/' + TYPES.FLOAT   + TYPES.FLOAT,        TYPES.FLOAT);
BINOP_TYPES.set('/' + TYPES.FLOAT   + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.FLOAT   + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

BINOP_TYPES.set('/' + TYPES.BIGINTEGER + TYPES.INTEGER,    TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGINTEGER + TYPES.FLOAT,      TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGINTEGER + TYPES.BIGINTEGER, TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGINTEGER + TYPES.BIGFLOAT,   TYPES.BIGFLOAT);

BINOP_TYPES.set('/' + TYPES.BIGFLOAT + TYPES.INTEGER,      TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGFLOAT + TYPES.FLOAT,        TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGFLOAT + TYPES.BIGINTEGER,   TYPES.BIGFLOAT);
BINOP_TYPES.set('/' + TYPES.BIGFLOAT + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);



export const PREUNOP_TYPES = new Map<string,string>();

// SIGN
PREUNOP_TYPES.set('-' + TYPES.INTEGER,       TYPES.INTEGER);
PREUNOP_TYPES.set('-' + TYPES.FLOAT,         TYPES.FLOAT);
PREUNOP_TYPES.set('-' + TYPES.BIGINTEGER,    TYPES.BIGINTEGER);
PREUNOP_TYPES.set('-' + TYPES.BIGFLOAT,      TYPES.BIGFLOAT);

PREUNOP_TYPES.set('+' + TYPES.INTEGER,       TYPES.INTEGER);
PREUNOP_TYPES.set('+' + TYPES.FLOAT,         TYPES.FLOAT);
PREUNOP_TYPES.set('+' + TYPES.BIGINTEGER,    TYPES.BIGINTEGER);
PREUNOP_TYPES.set('+' + TYPES.BIGFLOAT,      TYPES.BIGFLOAT);

// INCR
PREUNOP_TYPES.set('++' + TYPES.INTEGER,      TYPES.INTEGER);
PREUNOP_TYPES.set('++' + TYPES.FLOAT,        TYPES.FLOAT);
PREUNOP_TYPES.set('++' + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
PREUNOP_TYPES.set('++' + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

// DECR
PREUNOP_TYPES.set('--' + TYPES.INTEGER,      TYPES.INTEGER);
PREUNOP_TYPES.set('--' + TYPES.FLOAT,        TYPES.FLOAT);
PREUNOP_TYPES.set('--' + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
PREUNOP_TYPES.set('--' + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

// FACTORIAL
PREUNOP_TYPES.set('!'  + TYPES.INTEGER,      TYPES.INTEGER);
PREUNOP_TYPES.set('!'  + TYPES.FLOAT,        TYPES.FLOAT);
PREUNOP_TYPES.set('!'  + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
PREUNOP_TYPES.set('!'  + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);



export const POSTUNOP_TYPES = new Map<string,string>();

// INCR
POSTUNOP_TYPES.set('++' + TYPES.INTEGER,      TYPES.INTEGER);
POSTUNOP_TYPES.set('++' + TYPES.FLOAT,        TYPES.FLOAT);
POSTUNOP_TYPES.set('++' + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
POSTUNOP_TYPES.set('++' + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);

// DECR
POSTUNOP_TYPES.set('--' + TYPES.INTEGER,      TYPES.INTEGER);
POSTUNOP_TYPES.set('--' + TYPES.FLOAT,        TYPES.FLOAT);
POSTUNOP_TYPES.set('--' + TYPES.BIGINTEGER,   TYPES.BIGINTEGER);
POSTUNOP_TYPES.set('--' + TYPES.BIGFLOAT,     TYPES.BIGFLOAT);